In [ ]:
import pandas as pd

## Cargar datos

In [ ]:
from sklearn import datasets

iris_x, iris_y = datasets.load_iris(return_X_y=True)


In [ ]:
pd.DataFrame(iris_x)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_0, *[0], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_1, *[1], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_2, *[2], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_3, *[3], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_4, *[0], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_5, *[1], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_6, *[2], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_7, *[3], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plots(df, colname_pairs, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * 6 * figscale, 6 * figscale))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha, ax=ax)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(_df_8, *[[[0, 1], [1, 2], [2, 3]]], **{})
chart

In [ ]:
import numpy as np
np.sum(iris_y==2)

50

In [ ]:
dataset = list(zip(iris_x, iris_y))

In [ ]:
dataset

[(array([5.1, 3.5, 1.4, 0.2]), 0),
 (array([4.9, 3. , 1.4, 0.2]), 0),
 (array([4.7, 3.2, 1.3, 0.2]), 0),
 (array([4.6, 3.1, 1.5, 0.2]), 0),
 (array([5. , 3.6, 1.4, 0.2]), 0),
 (array([5.4, 3.9, 1.7, 0.4]), 0),
 (array([4.6, 3.4, 1.4, 0.3]), 0),
 (array([5. , 3.4, 1.5, 0.2]), 0),
 (array([4.4, 2.9, 1.4, 0.2]), 0),
 (array([4.9, 3.1, 1.5, 0.1]), 0),
 (array([5.4, 3.7, 1.5, 0.2]), 0),
 (array([4.8, 3.4, 1.6, 0.2]), 0),
 (array([4.8, 3. , 1.4, 0.1]), 0),
 (array([4.3, 3. , 1.1, 0.1]), 0),
 (array([5.8, 4. , 1.2, 0.2]), 0),
 (array([5.7, 4.4, 1.5, 0.4]), 0),
 (array([5.4, 3.9, 1.3, 0.4]), 0),
 (array([5.1, 3.5, 1.4, 0.3]), 0),
 (array([5.7, 3.8, 1.7, 0.3]), 0),
 (array([5.1, 3.8, 1.5, 0.3]), 0),
 (array([5.4, 3.4, 1.7, 0.2]), 0),
 (array([5.1, 3.7, 1.5, 0.4]), 0),
 (array([4.6, 3.6, 1. , 0.2]), 0),
 (array([5.1, 3.3, 1.7, 0.5]), 0),
 (array([4.8, 3.4, 1.9, 0.2]), 0),
 (array([5. , 3. , 1.6, 0.2]), 0),
 (array([5. , 3.4, 1.6, 0.4]), 0),
 (array([5.2, 3.5, 1.5, 0.2]), 0),
 (array([5.2, 3.4, 1

In [ ]:
import random

random.shuffle(dataset)

In [ ]:
dataset

[(array([5.1, 3.8, 1.5, 0.3]), 0),
 (array([4.5, 2.3, 1.3, 0.3]), 0),
 (array([5.6, 2.8, 4.9, 2. ]), 2),
 (array([5.9, 3. , 5.1, 1.8]), 2),
 (array([6.4, 3.2, 4.5, 1.5]), 1),
 (array([5. , 3.5, 1.6, 0.6]), 0),
 (array([6.3, 2.5, 5. , 1.9]), 2),
 (array([6.5, 3.2, 5.1, 2. ]), 2),
 (array([6.9, 3.1, 5.4, 2.1]), 2),
 (array([6. , 2.9, 4.5, 1.5]), 1),
 (array([4.6, 3.1, 1.5, 0.2]), 0),
 (array([6.7, 3.1, 5.6, 2.4]), 2),
 (array([6. , 3. , 4.8, 1.8]), 2),
 (array([5. , 3.3, 1.4, 0.2]), 0),
 (array([5.9, 3.2, 4.8, 1.8]), 1),
 (array([6.5, 3. , 5.2, 2. ]), 2),
 (array([6.9, 3.1, 4.9, 1.5]), 1),
 (array([5.5, 2.6, 4.4, 1.2]), 1),
 (array([4.7, 3.2, 1.6, 0.2]), 0),
 (array([4.9, 3.1, 1.5, 0.2]), 0),
 (array([6.2, 2.2, 4.5, 1.5]), 1),
 (array([6. , 3.4, 4.5, 1.6]), 1),
 (array([5.8, 2.8, 5.1, 2.4]), 2),
 (array([6.6, 3. , 4.4, 1.4]), 1),
 (array([5. , 2.3, 3.3, 1. ]), 1),
 (array([5.5, 2.5, 4. , 1.3]), 1),
 (array([6.4, 2.9, 4.3, 1.3]), 1),
 (array([4.4, 2.9, 1.4, 0.2]), 0),
 (array([5. , 3.2, 1

In [ ]:
iris_x = [d[0] for d in dataset]
iris_y = [d[1] for d in dataset]

## Separar los datos

In [ ]:
iris_x_train = iris_x[:-15]
iris_x_test = iris_x[-15:]

iris_y_train = iris_y[:-15]
iris_y_test = iris_y[-15:]

In [ ]:
iris_y_test[0]

2

## Entrenar el modelo

In [ ]:
from sklearn import linear_model

model = linear_model.LogisticRegression()
model.fit(iris_x_train, iris_y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
example = [iris_x_test[0]]
example

[array([6.3, 2.5, 5. , 1.9])]

In [ ]:
model.predict(example)

array([2])

## Evaluar el modelo

In [ ]:
from sklearn.metrics import mean_squared_error

diabetes_y_pred_test = model.predict(diabetes_x_test)
mse = mean_squared_error(diabetes_y_test, diabetes_y_pred_test)

print(mse)

1769.6424735565934


In [ ]:
import math

math.sqrt(mse)

42.06711867428756